B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W 
W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B 
B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W G W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B 
G W G W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W 
W G W G W B G B G W G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B 
G W G W G W B W B G W G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G B W B G 
W G W G W G W G W B G W G B W B G B W B G B W B G B W B G B W B G B W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B 
G W G W G W G W G W Y G W G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W 
W G W G W G W G W G W Y G W G B G W G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y 
G W G W G W G W G W G W B G W G W G W G Y W B W G W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G 
W G W G W G W G W G W G W B G W G W G W G Y W G W G W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B 
G W G W G W G W G W G W G W Y G W G W G W G B W G W G W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W 
W G W G W G W G W G W G W G W Y G W G W G B G Y W B W G B Y G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y 
B W G W Y B G W Y B G W Y B G W Y B W G Y G B W Y G B W Y B W G Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W 
Y B W G B Y W G B Y W G B Y W G B Y G W B Y G Y W B G Y W G B W B Y G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y 
W G B W Y B G W Y B G W Y B G W Y B W G Y B W G Y G B W Y B G Y W B W G Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W 
Y B G Y W G B Y W G B Y W G B Y W G B W B Y G W B Y G Y W G B W Y G B W B Y G Y W B G Y W B G Y W B G Y W B G Y W B G Y W B G Y 
W G B W Y B G W Y B G W Y B G W Y B G Y W B W G Y B W G Y B G Y W B G Y W B W G Y G B W Y G B W Y G B W Y G B W Y G B W Y G B W 
Y B G Y W G B Y W G B Y W G B Y W G B W Y G B W B Y G W B Y W G Y G B W Y G B W B Y G Y W B G Y W B G Y W B G Y W B G Y W B G Y 
W G B W Y B G W Y B G W Y B G W Y B G Y W B G Y W B W G Y B G W B Y G Y W B G Y W B W G Y G B W Y G B W Y G B W Y G B W Y G B W 
Y B G Y W G B Y W G B Y W G B Y W G B W Y G B W Y G B W B Y W G Y B W G Y G B W Y G B W B Y G Y W B G Y W B G Y W B G Y W B G Y 
W G B W Y B G W Y B G W Y B G W Y B G Y W B G Y W B G Y W B G W B Y G W B Y G Y W B G Y W B W G Y G B W Y G B W Y G B W Y G B W 
Y B G Y W G B Y W G B Y W G B Y W G B W Y G B W Y G B W Y G B Y W B W G Y B W G Y G B W Y G B W B Y G Y W B G Y W B G Y W B G Y 
W G B W Y B G W Y B G W Y B G W Y B G Y W B G Y W B G Y W B G W Y G B W B Y G W B Y G Y W B G Y W B W G Y G B W Y G B W Y G B W 
Y B G Y W G B Y W G B Y W G B Y W G B W Y G B W Y G B W Y G B Y W B G Y W B W G Y B W G Y G B W Y G B W B Y G Y W B G Y W B G Y 
W G B W Y B G W Y B G W Y B G W Y B G Y W B G Y W B G Y W B G W Y G B W Y G B W B Y G W B Y G Y W B G Y W B W G Y G B W Y G B W 
Y B G Y W G B Y W G B Y W G B Y W G B W Y G B W Y G B W Y G B Y W B G Y W B G Y W B W G Y B W G Y G B W Y G B W B Y G Y W B G Y 
W G B W Y B G W Y B G W Y B G W Y B G Y W B G Y W B G Y W B G W Y G B W Y G B W Y G B W B Y G W B Y G Y W B G Y W B W G Y G B W 
Y B G Y W G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W R B G W Y R B W G Y 
R G B W Y R G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W R B G W Y R B W G 
Y R G B W Y R G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W R B G W Y R B W 
G Y R G B W Y R G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W R B G W Y R B 
W G Y R G B W Y R G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W R B G W Y R 
B W G Y R G B W Y R G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W R B G W Y 
R B W G Y R G B W Y R G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W R B G W 
Y R B W G Y R G B W Y R G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W R B G 
W Y R B W G Y R G B W Y R G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W R B 
G W Y R B W G Y R G B W Y R G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W R 
B G W Y R B W G Y R G B W Y R G B Y W R B G W Y R B G W Y R B G W R Y G B W Y R B G W Y R B G W Y R B W G Y R B W G Y R B G Y W 
